on:
  push:
    branches:
      - release-please--branches--main

name: Module specific CHANGELOG.md generation

jobs:
  existing-versions-check:
    runs-on: ubuntu-latest
    if: |
      github.event.sender.login == 'ddixit14' && github.head_ref == 'release-please--branches--main' &&
      (contains(github.event.pull_request.labels.*.name, 'autorelease: pending'))
    steps:
      - run: |
          echo "Performing changelog.md generation steps..."