on:
  push:
    branches:
      - release-please--branches--main
  pull_request:

name: Module specific CHANGELOG.md generation

jobs:
  changelog-generation:
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
    steps:
      - name: Print Details
        run: |
          echo "Performing changelog.md generation steps..."
