on:
  push:
    branches:
      - main
  pull_request:

name: Module specific CHANGELOG.md generation

jobs:
  changelog-generation:
    runs-on: ubuntu-latest
    if: |
      github.event.sender.login == 'ddixit14' && github.head_ref == 'release-please--branches--main'
    steps:
      - name: Print Details
        run: |
          echo "Performing changelog.md generation steps..."
