on:
  push:
    branches:
      - release-please--branches--main

name: Module specific CHANGELOG.md generation

jobs:
  changelog-generation:
    runs-on: ubuntu-latest
    if: |
      github.head_ref == 'release-please--branches--main' &&
      (contains(github.event.pull_request.labels.*.name, 'autorelease: pending'))
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
      - run: |
          echo "$EVENT_CONTEXT" | jq .
          
