on:
  push:
    branches:
      - release-please--branches--main

name: Module specific CHANGELOG.md generation

jobs:
  changelog-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Print something
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          commit_sha=${{ github.sha }}
          pr_url=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/search/issues?q=sha:$commit_sha&type=pr" | jq -r '.items[0].html_url')
          
          pr_number=$(basename "$pr_url")
              labels_url=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$pr_url" | jq -r '.labels_url')

              pr_labels=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$labels_url" | jq -r '.[].name')
              if [[ $pr_labels == *"autorelease: pending"* ]]; then
                echo "The pull request has the specified label."
              else
                echo "The pull request does not have the specified label."
              fi