on:
  pull_request:
    types:
      - synchronize
  push:
    branches:
      - main

name: Module specific CHANGELOG.md generation

jobs:
  changelog-generation:
    runs-on: ubuntu-latest
    if: |
      github.event.sender.login == 'ddixit14' && github.head_ref == 'release-please--branches--main' &&
      (!contains(github.event.pull_request.labels.*.name, 'autorelease: snapshot'))
    steps:
      - name: Print Details
        run: |
          echo "Performing changelog.md generation steps..."
