on:
  push:
    branches:
      - release-please--branches--main

name: Module specific CHANGELOG.md generation

jobs:
  changelog-generation:
    runs-on: ubuntu-latest
    if: |
      github.event.sender.login == 'ddixit14'
    steps:
      - name: Print something
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          commit_sha=${{ github.sha }}
          pr_url=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/search/issues?q=sha:$commit_sha&type=pr" | jq -r '.items[0].html_url')
          pr_number=$(echo "$pr_url" | awk -F'/' '{print $(NF)}')
          labels_url="https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/labels"

          pr_labels=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$labels_url" | jq -r '.[].name')
          if [[ $pr_labels == *"autorelease: pending"* ]]; then
              echo "Running the changelog generation script...."
          else 
            echo "Not Running the changelog generation script...."
          fi