on:
  push:
    branches:
      - release-please--branches--main

name: Module specific CHANGELOG.md generation

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo "$EVENT_CONTEXT" | jq .
