on:
  push:
    branches:
      - release-please--branches--main

name: Module specific CHANGELOG.md generation

jobs:
  print_context:
    runs-on: ubuntu-latest
    run: |
      echo "${{ toJSON(github.event) }}" | jq .