on:
  push:
    branches:
      - release-please--branches--main

name: Module specific CHANGELOG.md generation

jobs:
  Changelog Generation:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "sender is : ${github.event.sender.login}" 
          echo "github head_ref is : ${github.event.sender.login}" 
          echo "github event details : ${github.event.pull_request.labels.*.name}" 
          echo "Performing changelog.md generation steps..."