on:
  push:
    branches:
      - release-please--branches--main

name: Module specific CHANGELOG.md generation

jobs:
  changelog-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Print Details
        run:
          echo "github event sender details: ${{ github.event.sender.login }}"
          echo "github head_ref is: ${{ github.head_ref }}"
          echo "github event details: ${{ github.event.pull_request.labels.*.name }}"