on:
  push:
    branches:
      - release-please--branches--main

name: Module specific CHANGELOG.md generation

jobs:
  changelog-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Print something
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          commit_sha=${{ github.sha }}
          pr_number=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/search/issues?q=sha:$commit_sha&type=pr" | jq -r '.items[0].html_url')
          
          echo " the pr is : ${pr_number}"
          
          if [ -n "$pr_number" ]; then
            pr_labels=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$pr_number/labels" | jq -r '.[].name')
            if [[ $pr_labels == *"autorelease: pending"* ]]; then
              echo "The commit is part of a pull request with the specified label."
            else
              echo "The commit is part of a pull request, but it does not have the specified label."
            fi
          else
            echo "The commit is not associated with any pull request."
          fi